// Code generated by "stringer -type=xdpAction -trimprefix=xdp"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[xdpAborted-0]
	_ = x[xdpDrop-1]
	_ = x[xdpPass-2]
	_ = x[xdpTx-3]
}

const _xdpAction_name = "AbortedDropPassTx"

var _xdpAction_index = [...]uint8{0, 7, 11, 15, 17}

func (i xdpAction) String() string {
	if i < 0 || i >= xdpAction(len(_xdpAction_index)-1) {
		return "xdpAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _xdpAction_name[_xdpAction_index[i]:_xdpAction_index[i+1]]
}
